- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  tasks:
    - name: print hostname
      ansible.builtin.debug:
        msg: my hostname are as {{ inventory_hostname}} and {{ ansible_hostname  }} with fqdn {{ ansible_fqdn }}
    - name: install kvm packages on Debian 10,9,..,Ubuntu 20.04,18.04,e.t.c
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - bridge-utils
        - genisoimage
        - libguestfs-tools
        - libnss-libvirt
        - libosinfo-bin
        - libvirt-clients
        - libvirt-daemon-system
        - libvirt-dev
        - python-lxml
        - python3-libvirt
        - qemu-kvm
        - qemu-utils
        - virt-top
        - virtinst  
      #become: true
