- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  tasks:
    - name: print hostname
      ansible.builtin.debug:
        msg: my hostname are as {{ inventory_hostname}} and {{ ansible_hostname  }} with fqdn {{ ansible_fqdn }}
    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: no
      
