- name: Deploy a web application
  hosts: kvm
  tasks:
    - name: print hostname
      ansible.builtin.debug:
        msg: my hostname are as {{ inventory_hostname}} and {{ ansible_hostname  }} with fqdn {{ ansible_fqdn }}
    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: no
    - name: display VM
      ansible.builtin.debug:
        msg: "{{ existing_vms }}"
      
